services:
  backend:
    build: ./backend
    expose:
      - "5000"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
